### ISSUE TITLE
Typos in JAVA_OPTS

### ISSUE THREAD

**Issue by camuffo** [geosolutions-it/charts#20]
There are small typos in the JAVA_OPTS value.
https://github.com/geosolutions-it/charts/blob/c1b3852a156ac4450deaf12874708a6814adb0c9/geoserver/latest/templates/statefulset.yaml#L142-L144

`-DGEOSERVER_CSRF_DISABLED=$(GEOSERVER_CSRF_DISABLED)\"` should be
`-DGEOSERVER_CSRF_DISABLED=\"$(GEOSERVER_CSRF_DISABLED)\"`

`-DGEOSERVER_DATA_DIR=$(GEOSERVER_DATA_DIR)\"` should be
`-DGEOSERVER_DATA_DIR=\"$(GEOSERVER_DATA_DIR)\"`

`-DGEOSERVER_AUDIT_PATH=$\"(GEOSERVER_AUDIT_PATH)\"` should be
`-DGEOSERVER_AUDIT_PATH=\"$(GEOSERVER_AUDIT_PATH)\"`

**Comment by camuffo** [comment]
PR https://github.com/geosolutions-it/charts/pull/21

**Comment by randomorder** [comment]
thanks @camuffo
