### ISSUE TITLE
Externalize environment.properties

### ISSUE THREAD

**Issue by camuffo** [geosolutions-it/charts#23]
We want to externalize the `environment.properties` file, so the chart user can declare env vars for GeoServer.

We have decided to create a Secret to hold the content of the file, and mount it somewhere like `/usr/local/tomcat/conf/environment.properties`.
The user sets the Secret content in the values file.

An annotation on the GS StatefulSet, set to the SHA sum of the Secret yaml, allows automatic Pod recreation upon Secret update.

**Comment by randomorder** [comment]
Hi @camuffo 
why is this one in review? what is to be reviewed? have you already implemented this?

**Comment by camuffo** [comment]
@randomorder because the related PR https://github.com/geosolutions-it/charts/pull/22 is yet to me merged.
